### ISSUE TITLE
Dados sensiveis

### ISSUE THREAD

**Issue by rzorzal** [silverbr23/prototipordgrastreio#1]
O arquivo ```config/.configs.json``` possui dados sensíveis para acesso a API's e etc ? Cuidado com isso.

**Comment by silverbr23** [comment]
Siiiim! Vê se o que eu to pensando e algo mt absurdo... mas eu queria um jeito de vincular esse arquivo ao projeto para que outras pessoas baixassem ele, no entanto n queria q este arquivo ficasse exposto... a unica solução seria atribuiro projeto como "Privado" mesmo, né?

**Comment by rzorzal** [comment]
Você pode usar o ```https://www.npmjs.com/package/dotenv-safe``` com isso você pode criar um arquivo ```.env.exemple``` e quando a pessoa fizer o fork do seu projeto, ela pode criar um arquivo ```.env``` com as definições de chaves deles. E lembrando que esse arquivo ```.env``` deve ficar fora do git, então insere ele no ```.gitignore```

**Comment by silverbr23** [comment]
Ah bom, top então! farei isso mais tarde hehe =D obg!
